# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:12
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('api', '0005_create_default_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[],
            options={
                'permissions': (('list_users', 'Can list users'), ),
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user', ),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ], ),
        migrations.AlterModelOptions(
            name='jog',
            options={
                'ordering': ('created', ),
                'permissions': (('list_jogs', 'Can list jogs'), )
            }, ),
    ]
