# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 20:35
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import Group, Permission


def assign_new_permissions(apps, schema_editor):
    # add new permissions to manager groupy
    new_manager_permissions = ['list_users', 'view_user']
    user_manager_group = Group.objects.filter(name='User manager').first()
    perms = Permission.objects.filter(codename__in=new_manager_permissions)
    user_manager_group.permissions.add(*perms)
    # add new permissions to admin group
    new_admin_permissions = new_manager_permissions + [
        'add_jog', 'change_jog', 'delete_jog'
    ]
    user_admin_group = Group(name='User admin')
    user_admin_group = Group.objects.filter(name='User admin').first()
    perms = Permission.objects.filter(codename__in=new_admin_permissions)
    user_admin_group.permissions.add(*perms)
    user_admin_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('api', '0005_create_default_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[],
            options={
                'permissions': (('list_users', 'Can list users'),
                                ('view_user', 'Can view user')),
                'proxy':
                True,
                'indexes': [],
            },
            bases=('auth.user', ),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ], ),
        migrations.AlterModelOptions(
            name='jog',
            options={
                'ordering': ('created', ),
                'permissions': (('list_jogs', 'Can list jogs'),
                                ('view_jog', 'Can view jog'))
            }, ),
        migrations.AlterField(
            model_name='jog',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='api.User'), ),
        migrations.RunPython(assign_new_permissions)
    ]
