# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 20:17
from __future__ import unicode_literals

from django.db import migrations


def assign_jog_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    permissions = ['view_jog', 'list_jogs']
    user_admin_group = Group.objects.filter(name='User admin').first()
    user_admin_group.save()
    perms = Permission.objects.filter(codename__in=permissions)
    user_admin_group.permissions.add(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170718_2035'),
    ]

    operations = [migrations.RunPython(assign_jog_permissions)]
