# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 01:28
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from api.models import USER_ADMIN_GROUP_NAME, USER_MANAGER_GROUP_NAME


def update_group_permissions(apps, schema_editor):
    perms = Permission.objects.filter(codename__in=['list_jogs', 'view_jogs'])
    group = Group.objects.filter(name=USER_ADMIN_GROUP_NAME).first()
    group.permissions.add(*perms)

    perms = Permission.objects.filter(codename__in=['list_users', 'view_user'])
    perms = Permission.objects.filter(codename__in='view_user')
    group = Group.objects.filter(name=USER_MANAGER_GROUP_NAME).first()
    group.permissions.add(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170717_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jog',
            options={
                'ordering': ('created', ),
                'permissions': (('list_jogs', 'Can list jogs'),
                                ('view_jog', 'Can view jog'))
            }, ),
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ('username', ),
                'permissions': (('list_users', 'Can list users'),
                                ('view_user', 'Can view user'))
            }, ),
        migrations.RunPython(update_group_permissions)
    ]
