# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:55
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_default_groups(apps, schema_editor):
    # create user manager group and default permissions
    user_manager_permissions = ['add_user', 'change_user', 'delete_user']
    user_manager_group = Group(name='User manager')
    user_manager_group.save()
    perms = Permission.objects.filter(codename__in=user_manager_permissions)
    user_manager_group.permissions.add(*perms)

    # create user admin group and default permissions
    user_admin_permissions = user_manager_permissions + [
        'add_jog', 'change_jog', 'delete_jog'
    ]
    user_admin_group = Group(name='User admin')
    user_admin_group.save()
    perms = Permission.objects.filter(codename__in=user_admin_permissions)
    user_admin_group.permissions.add(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170709_1709'),
    ]

    operations = [migrations.RunPython(create_default_groups)]
